LibraryLists/Models/ErrorViewModel.cs
namespace LibraryLists.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LibraryLists/Models/Favorites.cs
using System.ComponentModel.DataAnnotations;

namespace LibraryLists.Models
{
    public class Favorites
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "The Title is a required field.")]
        public string Title { get; set; }
        [Required(ErrorMessage = "The Authors Name is a required field.")]
        public string Author { get; set; }
        [Required(ErrorMessage = "ISBN is a required field.")]
        public int ISBN { get; set; }
    }
}

LibraryLists/Models/Library.cs
using System.ComponentModel.DataAnnotations;

namespace LibraryLists.Models
{
    public class Library
    {
        [Key]

        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Author { get; set; }
        [Required]
        public int ISBN { get; set; }

    }
}

LibraryLists/Models/LibraryFullList.cs
using System.ComponentModel.DataAnnotations;

namespace LibraryLists.Models
{
    public class LibraryFullList
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }

        public string Author { get; set; }

        public string Review { get; set; }

    }
}

LibraryLists/Controllers/FavoritesController.cs
using LibraryLists.Data;
using LibraryLists.Models;
using Microsoft.AspNetCore.Mvc;

namespace LibraryLists.Controllers
{
    public class FavoritesController : Controller
    {

        private readonly AppDbContext _db;

        public FavoritesController(AppDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Favorites> obj = _db.Favorites;
            _db.SaveChanges();
            return View(obj);
        }
    }
}

LibraryLists/Controllers/HomeController.cs
using LibraryLists.Data;
using LibraryLists.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LibraryLists.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }


        // IActionResult allows many return types rather than just a single return type.
        public IActionResult Index()
        {
            return View();
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LibraryLists/Controllers/LibraryController.cs
using LibraryLists.Data;
using LibraryLists.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace LibraryLists.Controllers
{
    public class LibraryController : Controller
    {
        private readonly AppDbContext _db;

        public LibraryController(AppDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Library> ObjList = _db.Library;
            return View(ObjList);
        }

        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        //Action MUST be explicidly defined.
        [HttpPost]
        public IActionResult Create(Library obj)

        {
            if (ModelState.IsValid)
            {
                _db.Library.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Book Created Successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }


        //GET
        // IActionResult allowing more than one return type.
        // NotFoundResult.

        public IActionResult Edit(int ? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDb = _db.Library.Find(id);
            return View(categoryFromDb);
        }

        //POST
        //ADDITIONAL _db.Update(obj);

        [HttpPost]        
        public IActionResult Edit(Library obj)

        {
            if (ModelState.IsValid)
            {
                _db.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Book Updated Successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var categoryFromDb = _db.Library.Find(id);
            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Library obj)

        {
            if (ModelState.IsValid)
            {
                _db.Remove(obj);
                _db.SaveChanges();
                TempData["success"] = "Book Deleted Successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }


    

    //GET
    public IActionResult Add(int ? id)
    {
        if (id == null || id == 0)
        {
            return NotFound();
        }

        var categoryFromDb = _db.Library.Find(id);
        if (categoryFromDb == null)
        {
            return NotFound();
        }
        return View(categoryFromDb);
    }

     //POST
     // Redirecting to The Favorites Controller.
     // SqlException: Cannot insert explicit value for identity column in table 'Library' when IDENTITY_INSERT is set to OFF.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Add(Favorites obj)

    {
        if (ModelState.IsValid)
        {
                _db.Favorites.Add(obj);
               TempData["success"] = "Book Added to Favorites";
              return RedirectToAction("Index", "Favorites");
        }
        return View(obj);
    }

}
}

LibraryLists/Views/Favorites/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model IEnumerable<Favorites>


@{
    ViewData["Title"] = "Home Page";
}


<partial name="_Notification"/>

<div class="container p-2">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="">Favorites</h2>
        </div>
    </div>
    <br />


<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th class="col-1">
                Book ID
            </th>
            <th class="col-3">
                Title
            </th>
            <th class="col-3">
                Author
            </th>
       
            <th class="col-2">
                ISBN
            </th>
           

        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td class="m-1">
                    @obj.Id
                </td>
                <td class="m-1">
                    @obj.Title
                </td>
                 <td class="m-1">
                    @obj.Author
                </td>
                <td class="m-1">
                    @obj.ISBN
                </td>
            </tr>
        }
    </tbody>
</table>

</div>

LibraryLists/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="text-center">
    <br />
    <br />
    <br />
    <br />
    <div>
        <h2>Stay Updated</h2>
        <p>Get The Latest News on Your Favorite Books!</p>
    </div>
    <div class="btn-group m-1">
    <input class="bg-outline-primary" type="email" placeholder="Email"/>
    <button class="btn btn-dark" href ="mailto: haydenbruceanderson12@gmail.com" type="submit">Submit</button>
    </div>
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <h5>Connect With Us</h5>
    <div class="">
        <a style="color:grey"><i class="bi bi-linkedin"></i></a>
        <a style="color:grey; margin-left:10px"><i class="bi bi-facebook"></i></a>
        <a style="color:grey; margin-left:10px"><i class="bi bi-telephone-fill"></i></a>
    </div>
</div>

LibraryLists/Views/Library/Add.cshtml
@model Library

@{
    ViewData["Title"] = "Home Page";
}

<form method="post" asp-action="Add">
    <div class=" border p-3 mt-2">
        <div class="row pb-2">
            <h2 class="">Add Book to Favorites</h2>
        </div>
        <div class="p-1 mt-1">
            <label asp-for="Title"></label>
            <input class="form-control" asp-for="Title"/>
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
           <div class="p-1 mt-1">
            <label asp-for="Author"></label>
            <input class="form-control" asp-for="Author"/>
            <span asp-validation-for="Author" class="text-danger"></span>

        </div>
           <div class="p-1 mt-1">
            <label asp-for="ISBN"></label>
            <input class="form-control" asp-for="ISBN"/>
            <span asp-validation-for= "ISBN"  class="text-danger"></span>

        </div>
        <a asp-controller="Favorites" asp-action="Index"><button type="submit" class="btn btn-secondary m-1" style="width:150px">Add to Favorites</button></a>
        <a class="btn m-1 btn-outline-secondary ml-2 asp-controller="Library" asp-action="Index" style="width:150px">Go Back</a>
    </div>
</form>

LibraryLists/Views/Library/Create.cshtml
@model Library

@{
    ViewData["Title"] = "Home Page";
}

<form method="post">
    <div class=" border p-3 mt-2">
        <div class="row pb-2">
            <h2 class="">Create Book</h2>
        </div>
        <div class="p-1 mt-1">
            <label asp-for="Title"></label>
            <input class="form-control" asp-for="Title"/>
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
           <div class="p-1 mt-1">
            <label asp-for="Author"></label>
            <input class="form-control" asp-for="Author"/>
            <span asp-validation-for="Author" class="text-danger"></span>

        </div>
           <div class="p-1 mt-1">
            <label asp-for="ISBN"></label>
            <input class="form-control" asp-for="ISBN"/>
            <span asp-validation-for= "ISBN"  class="text-danger"></span>

        </div>
        <button type="submit" class="btn btn-secondary m-1" style="width:150px">Create</button>
        <a class="btn m-1 btn-outline-secondary ml-2 asp-controller="Library" asp-action="Index" style="width:150px">Go Back</a>
    </div>
</form>

LibraryLists/Views/Library/Delete.cshtml
@model Library

@{
    ViewData["Title"] = "Home Page";

}

<form method="post" asp-action="Delete">
    <div class=" border p-3 mt-2">
        <div class="row pb-2">
            <h2 class="">Delete Book</h2>
        </div>
        <div class="p-1 mt-1">
            <label asp-for="Title"></label>
            <input class="form-control" asp-for="Title" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
           <div class="p-1 mt-1">
            <label asp-for="Author"></label>
            <input class="form-control" asp-for="Author" />
            <span asp-validation-for="Author" class="text-danger"></span>

        </div>
           <div class="p-1 mt-1">
            <label asp-for="ISBN"></label>
            <input class="form-control" asp-for="ISBN"/>
            <span asp-validation-for= "ISBN"  class="text-danger"></span>

        </div>
        <button type="submit" class="btn btn-secondary m-1" style="width:150px">Delete</button>
        <a class="btn m-1 btn-outline-secondary ml-2 asp-controller="Library" asp-action="Index" style="width:150px">Go Back</a>
    </div>
</form>

LibraryLists/Views/Library/Edit.cshtml
@model Library

@{
    ViewData["Title"] = "Home Page";
}

<form method="post" asp-action="Edit">
    <div class=" border p-3 mt-2">
        <div class="row pb-2">
            <h2 class="">Edit Book</h2>
        </div>
        <div class="p-1 mt-1">
            <label asp-for="Title"></label>
            <input class="form-control" asp-for="Title"/>
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
           <div class="p-1 mt-1">
            <label asp-for="Author"></label>
            <input class="form-control" asp-for="Author"/>
            <span asp-validation-for="Author" class="text-danger"></span>

        </div>
           <div class="p-1 mt-1">
            <label asp-for="ISBN"></label>
            <input class="form-control" asp-for="ISBN"/>
            <span asp-validation-for= "ISBN"  class="text-danger"></span>

        </div>
        <button type="submit" class="btn btn-secondary m-1" style="width:150px">Update</button>
        <a class="btn m-1 btn-outline-secondary ml-2 asp-controller="Library" asp-action="Index" style="width:150px">Go Back</a>
    </div>
</form>

LibraryLists/Views/Library/Index.cshtml
@model IEnumerable<Library>
@{
    ViewData["Title"] = "Home Page";
}


<partial name="_Notification"/>

<div class="container p-2">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="">Library Listings</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Library" asp-action="Create"><button class="btn btn-secondary">Create New</button></a>
        </div>
    </div>
    <br />


<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th class="col-1">
                Book ID
            </th>
            <th class="col-3">
                Title
            </th>
            <th class="col-3">
                Author
            </th>
       
            <th class="col-2">
                ISBN
            </th>
            <th class="col-3">
                Options
            </th>
            <th class="col-1">
                Favorite
            </th>
           

        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td class="m-1">
                    @obj.Id
                </td>
                <td class="m-1">
                    @obj.Title
                </td>
                 <td class="m-1">
                    @obj.Author
                </td>
                <td class="m-1">
                    @obj.ISBN
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                    <a class="btn btn-warning m-1" style="width:45px" asp-controller="Library" asp-action="Edit" asp-route-id="@obj.Id">Edit </a>
                    <a class="btn btn-danger m-1" style="width:45px" asp-controller="Library" asp-action="Delete" asp-route-id="@obj.Id">Delete </a>
                    </div>
                </td>
                <td>
                    <a class="btn btn-success m-1" asp-controller="Library" asp-action="Add" asp-route-id="@obj.Id">Add</a>
                </td>
            </tr>
        }
    </tbody>
</table>

</div>

LibraryLists/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryListings</title>
     <link href="//cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibraryLists.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"/>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LibraryListings</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Library" asp-action="Index">Library</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Favorites" asp-action="Index">Favorites</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - LibraryListings
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

LibraryLists/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}

@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
     <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
}